name: custom_text_example
description: An example app of custom_text.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  custom_text:
    path: ../

  collection: 1.17.0
  go_router: ^6.0.6
  google_fonts: ^4.0.3
  url_launcher: ^6.1.9

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - lib/examples/
