name: custom_text_example
description: An example app of custom_text.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  custom_text:
    path: ../

  collection: ^1.17.0
  device_info_plus: ^9.0.1
  go_router: ^7.1.1
  google_fonts: ^4.0.4
  highlight: ^0.7.0
  positioned_popup:
    git:
      url: https://github.com/kaboc/positioned-popup.git
      ref: 28af814a9dcb1623fce3a7301d10e76006afbf94
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - lib/examples/
