name: custom_text_example
description: An example app of custom_text.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

  custom_text:
    path: ../
  google_fonts: ^2.1.0

flutter:
  uses-material-design: true

  assets:
    - lib/examples/
