name: custom_text_example
description: An example app of custom_text.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  custom_text:
    path: ../

  collection: ^1.18.0
  device_info_plus: ^9.1.2
  go_router: ^14.2.3
  # 6.2.0 has a bug and 6.2.1 does not support Dart 3.2.
  # https://github.com/material-foundation/flutter-packages/issues/567
  google_fonts: 6.1.0
  highlight: ^0.7.0
  positioned_popup:
    git:
      url: https://github.com/kaboc/positioned-popup.git
      ref: 28af814a9dcb1623fce3a7301d10e76006afbf94
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0
  go_router_builder: ^2.7.1

flutter:
  uses-material-design: true

  assets:
    - lib/examples/src/
