name: custom_text_example
description: An example app of custom_text.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  custom_text:
    path: ../
  go_router: ^6.0.1
  google_fonts: ^3.0.1
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - lib/examples/
