name: custom_text
description: Highly customisable text widget and controller to enable styling and gesture actions.
version: 2.0.1
repository: https://github.com/kaboc/flutter_custom_text

topics:
  - text

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.10.0
  text_parser: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

screenshots:
  - description: 'Applying styles and triggering actions by gestures.'
    path: screenshots/unique_styles_and_actions.gif
  - description: 'Changing mouse cursor and text style on hover.'
    path: screenshots/mouse_cursor_and_text_style_on_hover.gif
  - description: 'Showing a popup at the position of a mouse enter event.'
    path: screenshots/event_position.gif
  - description: 'CustomTextEditingController enables text styling and actions in editable text.'
    path: screenshots/custom_text_editing_controller.gif
  - description: 'Support for an external parser allows a wider variety of use cases.'
    path: screenshots/external_parser.gif
