name: custom_text
description: A highly customisable text widget that allows styles and gestures to be applied to strings in it flexibly.
version: 0.5.1
repository: https://github.com/kaboc/flutter_custom_text

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

  text_parser: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
