name: custom_text
description: A highly customisable text widget that allows styles and gestures to be applied to strings in it flexibly.
version: 0.6.0-dev.6
repository: https://github.com/kaboc/flutter_custom_text

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.7.0
  text_parser: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
