name: custom_text
description: A highly customisable text widget that allows styles and tap gestures to be applied to strings in it flexibly.
version: 0.3.1
homepage: https://github.com/kaboc/flutter_custom_text

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

  text_parser: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
