name: Gh-Pages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - uses: bluefireteam/flutter-gh-pages@v8
        with:
          workingDir: example
          baseHref: /flutter_custom_text/
